
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeChange } from '../components/ClientSideRender/ThemeChange'
import { ThemeProvider } from '../ThemeProvider'
import {notFound} from 'next/navigation';

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const locales = ['en', 'pl'];
export default function RootLayout({children, params: {locale}}) {
    // Validate that the incoming `locale` parameter is valid
    const isValidLocale = locales.some((cur) => cur === locale);
    if (!isValidLocale) notFound();
  return (
    <html lang={locale}>
      <body className={`${inter.className} dark:bg-slate-900`}>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            {children}
          </ThemeProvider>
      </body>
    </html>
  )
}
